# Generated by Django 4.0.3 on 2023-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_num', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('phone_num', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=15)),
                ('user_pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('phone_num', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('관리자', '관리자'), ('의사', '의사'), ('물리 치료사', '물리 치료사'), ('기타 의료진', '기타 의료진'), ('환자', '환자'), ('간호사', '간호사')], max_length=10)),
            ],
        ),
    ]
