# Generated by Django 4.0.3 on 2023-10-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_num',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_num',
            new_name='id',
        ),
    ]
