# Generated by Django 4.2.6 on 2023-10-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_patient_num_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRecords',
            fields=[
                ('diagnosis_code', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField()),
                ('symptoms', models.CharField(max_length=55)),
                ('diagnosis', models.CharField(max_length=55)),
                ('comments', models.CharField(max_length=55)),
                ('prescription_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='patient_num',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_num',
        ),
        migrations.CreateModel(
            name='TreatmentRecords',
            fields=[
                ('treatment_code', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('treatment_type', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('time', models.IntegerField()),
                ('diagnosis_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.diagnosticrecords')),
                ('patient_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.patient')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecords',
            fields=[
                ('test_code', models.AutoField(primary_key=True, serialize=False)),
                ('MuscleMass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BodyFatMass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Muscular_strength', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cardio_endurance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flexibility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('patient_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_code', models.AutoField(primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=15)),
                ('dosage', models.IntegerField()),
                ('times', models.IntegerField()),
                ('days', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('diagnosis_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.diagnosticrecords')),
                ('patient_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.patient')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='MediaRecords',
            fields=[
                ('data_code', models.AutoField(primary_key=True, serialize=False)),
                ('inbody_url', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('xray_url', models.CharField(max_length=255)),
                ('Field4', models.CharField(max_length=255)),
                ('patient_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='base.testrecords')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecords',
            fields=[
                ('exercise_code', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('iteration', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_type', models.CharField(choices=[('strength', '무산소'), ('cardio', '유산소')], max_length=10)),
                ('diagnosis_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.diagnosticrecords')),
                ('patient_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.patient')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosticrecords',
            name='patient_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AddField(
            model_name='diagnosticrecords',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user'),
        ),
    ]
