# Generated by Django 4.2.6 on 2023-10-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_diagnosticrecords_rename_id_patient_patient_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticrecords',
            name='patient_num',
        ),
        migrations.RemoveField(
            model_name='diagnosticrecords',
            name='user_num',
        ),
        migrations.RemoveField(
            model_name='exerciserecords',
            name='diagnosis_code',
        ),
        migrations.RemoveField(
            model_name='exerciserecords',
            name='patient_num',
        ),
        migrations.RemoveField(
            model_name='exerciserecords',
            name='user_num',
        ),
        migrations.RemoveField(
            model_name='mediarecords',
            name='patient_num',
        ),
        migrations.RemoveField(
            model_name='mediarecords',
            name='test_code',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis_code',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_num',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user_num',
        ),
        migrations.RemoveField(
            model_name='testrecords',
            name='patient_num',
        ),
        migrations.RemoveField(
            model_name='treatmentrecords',
            name='diagnosis_code',
        ),
        migrations.RemoveField(
            model_name='treatmentrecords',
            name='patient_num',
        ),
        migrations.RemoveField(
            model_name='treatmentrecords',
            name='user_num',
        ),
    ]
