# Generated by Django 4.2.6 on 2023-10-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_diagnosticrecords_patient_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_num',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_num',
            new_name='id',
        ),
    ]
