# Generated by Django 4.2.6 on 2023-10-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_patient_num_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticrecords',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AddField(
            model_name='diagnosticrecords',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.user'),
        ),
        migrations.AddField(
            model_name='exerciserecords',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.patient'),
        ),
        migrations.AddField(
            model_name='exerciserecords',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.user'),
        ),
        migrations.AddField(
            model_name='mediarecords',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.user'),
        ),
        migrations.AddField(
            model_name='testrecords',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AddField(
            model_name='treatmentrecords',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.patient'),
        ),
        migrations.AddField(
            model_name='treatmentrecords',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.user'),
        ),
    ]
