# Generated by Django 4.2.6 on 2023-10-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_diagnosticrecords_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='comments',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='prescription_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='symptoms',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticrecords',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.user'),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('strength', '무산소'), ('cardio', '유산소')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.patient'),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='운동', to='base.user'),
        ),
        migrations.AlterField(
            model_name='exerciserecords',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mediarecords',
            name='Field4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediarecords',
            name='inbody_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediarecords',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AlterField(
            model_name='mediarecords',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediarecords',
            name='xray_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='times',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='처방', to='base.user'),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='BodyFatMass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='MuscleMass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='Muscular_strength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='agility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='cardio_endurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='flexibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patient'),
        ),
        migrations.AlterField(
            model_name='treatmentrecords',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecords',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecords',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.patient'),
        ),
        migrations.AlterField(
            model_name='treatmentrecords',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecords',
            name='treatment_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecords',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='치료', to='base.user'),
        ),
    ]
